.TH SEJECT 1 "April 2025" "safe-eject 1.0" "User Commands"

.SH NAME
seject \- Safely eject USB drive

.SH SYNOPSIS
.B \fBseject\fR [OPTIONS] \fIdevice\fR

.SH DESCRIPTION
A command-line utility to safely unmount and poweroff USB mass-storage devices.
.PP
A bash script that mimics the behavior of “Safely Remove USB Drive” in modern
Linux Desktops. It unmounts all partitions, flushes write cache, and powers off
the USB drive, using udisks2 under the hood.
.PP
It ensures data integrity by flushing the write cache, and confirming that no
partitions remain mounted or in use, so the USB drive can be safely unplugged.
.PP
The command accepts a single argument, which can be the USB drive device
(e.g. /dev/sdX), or a USB partition device (e.g. /dev/sdXN). In both cases,
the behavior is the same.

.SH FEATURES
.TP
\(bu Unmounts all mounted partitions of the USB drive
.TP
\(bu Waits if partitions are busy before unmounting
.TP
\(bu Flushes write cache via \fBsync\fR
.TP
\(bu Uses \fBudisksctl power-off\fR to spin down and power off USB devices

.SH ARGUMENTS
.TP
\fIdevice\fR
USB storage device path (e.g. /dev/sdX)
.br
or USB storage partition path (e.g. /dev/sdXN)

.SH OPTIONS
.TP
\fB-d\fR, \fB--debug\fR
Enable debug output
.TP
\fB-h\fR, \fB--help\fR
Display usage information
.TP
\fB-v\fR, \fB--version\fR
Show current version

.SH EXAMPLES
.TP
Find your USB drive:
.B
lsblk -ln -o NAME,SIZE,TYPE,MOUNTPOINT
.TP
Safely eject USB drive by device path:
.B
seject /dev/sdX
.TP
Safely eject USB drive by partition path:
.B
seject /dev/sdXN

.SH REQUIREMENTS
.TP
.BR udisksctl (1)
Provided by \fIudisks2\fR package
.TP
.BR fuser (1)
Provided by \fIpsmisc\fR package
.TP
.BR sync (1)
Provided by \fIcoreutils\fR package
.TP
.BR lsblk (8)
Provided by \fIutil-linux\fR package

.SH SEE ALSO
.BR eject (1)

.SH LICENSE
This project is licensed under the MIT License.
.br
It is free and open source software: you can freely use it, change it, and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.

.SH PROJECT PAGE
https://github.com/rogeriooferraz/seject

.SH AUTHOR
Rogerio O. Ferraz <rogerio.o.ferraz@gmail.com>
