.TH SEJECT 1 "April 2025" "Version 1.0" "User Commands"
.SH NAME
seject \- Safely eject USB drives

.SH SYNOPSIS
.B seject
.RI drive\ |\ partition

.SH DESCRIPTION
.B seject
is a command-line utility to safely unmount and power off USB drives.
.PP
It ensures data integrity by flushing the write cache, and confirming that no
partitions remain mounted or in use, so the USB drive can be safely unplugged.
.PP
The command accepts a single argument, which can be the USB drive device
(e.g. /dev/sdX), or a USB partition device (e.g. /dev/sdXN). In both cases,
the behavior is the same.

.SH FEATURES
.TP
\(bu Unmounts all mounted partitions of the USB drive
.TP
\(bu Waits if partitions are busy before unmounting
.TP
\(bu Flushes write cache via \fBsync\fR
.TP
\(bu Uses \fBudisksctl power-off\fR to spin down and power off USB devices

.SH ARGUMENTS
.TP
.I drive
The full path to the USB device (e.g. /dev/sdX)
.TP
.I partition
The full path to a partition on the USB device (e.g. /dev/sdXN)
.TP
Both forms are accepted and treated the same

.SH OPTIONS
None

.SH EXAMPLES

.EE
Find your USB drive:
.EE
$ lsblk -ln -o NAME,SIZE,TYPE,MOUNTPOINT

.EE
Safely eject USB drive by device path:
.EE
$ seject /dev/sdX

.EE
Safely eject USB drive by a partition path:
.EE
$ seject /dev/sdXN

.SH REQUIREMENTS
.TP
.BR udisksctl (1)
Provided by the
.IR udisks2
package

.TP
.BR fuser (1),
Provided by the
.IR psmisc
package

.TP
.BR sync (1)
Provided by the
.IR coreutils
package

.TP
.BR lsblk (8)
Provided by the
.IR util-linux
package

.SH SEE ALSO
.BR eject (1)

.SH AUTHOR
Rogerio O. Ferraz <rogerio.o.ferraz@gmail.com>

.SH LICENSE
MIT License
.br
This is free software: you are free to change and redistribute it
.br
There is NO WARRANTY, to the extent permitted by law
.br
Copyright (c) 2025 Rogerio O. Ferraz <rogerio.o.ferraz@gmail.com>

.SH PROJECT PAGE
https://github.com/rogeriooferraz/seject
